import { aiSimulationDelayMs, documentSimulationDelayMs } from "./constants";
import type { ClaimNodeRegistryItem } from "./registry";
import type {
  ClaimDashboardApiNode,
  DocumentAnalysisResult,
  ExplainResult,
} from "./types";

function wait(durationMs: number) {
  return new Promise((resolve) => {
    setTimeout(resolve, durationMs);
  });
}

function getExplainSuggestedAction(node: ClaimDashboardApiNode) {
  if ("actionRequired" in node.raw) {
    return node.raw.actionRequired;
  }

  if (node.status === "Pending") {
    return "Keep this step visible and wait for the owning team to complete it.";
  }

  if (node.status === "In Progress") {
    return "No new claimant upload is needed yet, but this stage should stay monitored.";
  }

  return "No immediate claimant action is required for this step.";
}

function getExplainConfidence(node: ClaimDashboardApiNode) {
  switch (node.status) {
    case "Completed":
    case "Report Completed":
      return "High confidence from completed claim data";
    case "In Progress":
      return "Medium confidence while the step is still moving";
    case "Pending":
      return "Action-sensitive confidence until the blocker is cleared";
  }
}

export async function simulateExplainResult(
  node: ClaimDashboardApiNode,
  definition: ClaimNodeRegistryItem,
): Promise<ExplainResult> {
  await wait(aiSimulationDelayMs);

  const spotlight =
    node.fields.find((field) => field.key === definition.spotlightFieldKey) ??
    node.fields[0];
  const highlights = [
    `This step belongs to ${definition.eyebrow.toLowerCase()} and is currently marked ${node.status.toLowerCase()}.`,
    spotlight
      ? `${spotlight.label}: ${spotlight.value}`
      : "No spotlight field is available for this step.",
    node.fields[1]
      ? `${node.fields[1].label}: ${node.fields[1].value}`
      : "The payload only exposes a minimal field set here.",
  ];

  return {
    heading: `${node.title} in plain language`,
    summary: `${definition.description} ${node.summary} This explanation is simulated from the route-local claim payload, not generated by an external model.`,
    highlights,
    suggestedAction: getExplainSuggestedAction(node),
    confidenceLabel: getExplainConfidence(node),
  };
}

function getFileExtension(fileName: string) {
  const extension = fileName.split(".").at(-1);
  return extension?.toLowerCase() ?? "";
}

export async function simulateDocumentAnalysis(
  file: File,
): Promise<DocumentAnalysisResult> {
  await wait(documentSimulationDelayMs);

  const normalizedName = file.name.toLowerCase();
  const extension = getFileExtension(normalizedName);
  const allowedExtensions = new Set(["pdf", "png", "jpg", "jpeg", "webp"]);
  const hasCertificateKeyword =
    normalizedName.includes("certificate") ||
    normalizedName.includes("occupational") ||
    normalizedName.includes("occupation") ||
    normalizedName.includes("belge");
  const looksLikeDraft =
    normalizedName.includes("draft") ||
    normalizedName.includes("scan") ||
    normalizedName.includes("photo");

  if (!allowedExtensions.has(extension)) {
    return {
      state: "rejected",
      title: "Document rejected",
      summary:
        "The simulated validator only accepts PDF or common image formats for occupational certificate review.",
      checks: [
        `Detected extension: .${extension || "unknown"}`,
        "Allowed formats: PDF, PNG, JPG, JPEG, WEBP",
        "Please upload a cleaner export or scan of the certificate.",
      ],
    };
  }

  if (!hasCertificateKeyword || looksLikeDraft) {
    return {
      state: "warning",
      title: "Manual review recommended",
      summary:
        "The file format is acceptable, but the filename does not strongly indicate a finalized occupational certificate.",
      checks: [
        `Detected extension: .${extension}`,
        looksLikeDraft
          ? "Filename suggests a draft, scan, or informal capture."
          : "Certificate keywords were not found in the filename.",
        "A claims handler would likely request confirmation before clearing the deduction step.",
      ],
    };
  }

  return {
    state: "accepted",
    title: "Document accepted",
    summary:
      "The simulated analyzer found a supported file type and filename cues consistent with an occupational certificate.",
    checks: [
      `Detected extension: .${extension}`,
      "Certificate-related keywords were found in the filename.",
      "No obvious filename red flags were detected for this submission.",
    ],
  };
}
